import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        "display": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      colors: {
        "inverse-surface": "#303032",
        "on-secondary-fixed": "#1a1c1d",
        "on-error": "#ffffff",
        "secondary": "#5d5e60",
        "tertiary": "#5d5e63",
        "surface-variant": "#e4e2e4",
        "surface-tint": "#106c48",
        "secondary-fixed": "#e2e2e4",
        "primary-fixed": "#a1f4c6",
        "surface-dim": "#dcd9dc",
        "tertiary-fixed-dim": "#c6c6cb",
        "surface-container-low": "#f6f3f5",
        "on-secondary-fixed-variant": "#454749",
        "on-primary-fixed-variant": "#005234",
        "surface-container-highest": "#e4e2e4",
        "on-tertiary-fixed-variant": "#45474b",
        "on-tertiary-fixed": "#1a1c1f",
        "surface-container-high": "#eae7ea",
        "on-primary": "#ffffff",
        "primary-container": "#9cefc1",
        "on-tertiary-container": "#606165",
        "on-surface-variant": "#3f4942",
        "surface-container": "#f0edef",
        "background": "#ffffff",
        "surface-bright": "#ffffff",
        "secondary-fixed-dim": "#c6c6c8",
        "surface-container-lowest": "#ffffff",
        "surface": "#ffffff",
        "on-background": "#1b1b1d",
        "tertiary-fixed": "#e2e2e7",
        "error": "#ba1a1a",
        "primary": "#106c48",
        "secondary-container": "#dfdfe1",
        "on-primary-container": "#156f4a",
        "tertiary-container": "#dddde2",
        "inverse-primary": "#85d7ab",
        "on-surface": "#1b1b1d",
        "on-secondary-container": "#616365",
        "outline": "#6f7a72",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3f0f2",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#85d7ab",
        "outline-variant": "#bec9c0",
        "on-primary-fixed": "#002112",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "unit": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "24px",
      },
    },
  },
  plugins: [],
};
export default config;
